_wandb:
    value:
        cli_version: 0.24.1
        e:
            dfi3aowipl1587p88t28jbnot83p5k6p:
                args:
                    - --data_root
                    - data
                    - --num_classes
                    - "8"
                    - --fusion
                    - gated
                    - --use_wavlm
                    - --audio_ckpt
                    - outputs/best_audio.pt
                    - --video_ckpt
                    - outputs/best_video.pt
                    - --two_stage_training
                    - --stage1_epochs
                    - "5"
                    - --lr
                    - "3e-4"
                    - --audio_backbone_lr
                    - "1e-5"
                    - --video_backbone_lr
                    - "1e-5"
                    - --fusion_unfreeze_wavlm_layers
                    - "2"
                    - --fusion_unfreeze_video_blocks
                    - "1"
                    - --epochs
                    - "30"
                    - --batch_size
                    - "8"
                    - --weight_decay
                    - "1e-4"
                    - --use_cosine_annealing
                    - --early_stopping_patience
                    - "8"
                    - --num_workers
                    - "-1"
                    - --wandb
                codePath: src/train.py
                codePathLocal: src/train.py
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1081101176832"
                        used: "59584819200"
                email: wionerlol@gmail.com
                executable: /home/louis/projects/MultimodalEmotionRecognition/.venv/bin/python3
                git:
                    commit: d60c7ef782183f53b696349c9dc8c6bdee73f508
                    remote: https://github.com/Wionerlol/MultimodalEmotionRecognition.git
                gpu: NVIDIA GeForce RTX 5080 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5080 Laptop GPU
                      uuid: GPU-40be5801-0aff-1b94-3ecc-fdefefc4b764
                host: MoonCell
                memory:
                    total: "16466980864"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/louis/projects/MultimodalEmotionRecognition/src/train.py
                python: CPython 3.10.19
                root: /home/louis/projects/MultimodalEmotionRecognition
                startedAt: "2026-02-10T17:06:55.453828Z"
                writerId: dfi3aowipl1587p88t28jbnot83p5k6p
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.19
            "5": 0.24.1
            "6": 5.1.0
            "12": 0.24.1
            "13": linux-x86_64
batch_size:
    value: 8
cosine_annealing:
    value: true
epochs:
    value: 30
fusion:
    value: gated
lr:
    value: 0.0003
num_classes:
    value: 8
split_mode:
    value: stratified
